'use client';
import { useEffect, useState } from 'react';
import Image from 'next/image';import Link from 'next/link';import {ArrowUpRight} from 'lucide-react';import {CatalogCard} from '@/components/CatalogCard';import {products} from '@/lib/catalog';

export default function Home() {
  const [featured, setFeatured] = useState<any[]>([]);
  useEffect(() => { products({featured: true}).then(setFeatured) }, []);

  return <><section className="hero wrap"><div className="hero-copy"><p className="eyebrow">ART · HANDMADE · PERSONAL</p><h1>Small creations,<br/><em>made with feeling.</em></h1><p className="lede">Original artwork, considered keepsakes, and commissions made especially for your world.</p><div className="actions"><Link className="button" href="/shop">Shop the collection <ArrowUpRight size={17}/></Link><Link className="text-button" href="/commissions">Commission an artwork</Link></div></div><div className="hero-art"><Image priority src="/images/artist-at-work.png" alt="Artist painting in a calm studio" fill sizes="(max-width:800px) 100vw, 50vw"/><div className="art-note">Made in small,<br/>thoughtful batches.</div></div></section><section className="wrap section"><div className="section-heading"><div><p className="eyebrow">A LITTLE SOMETHING</p><h2>Shop by feeling</h2></div><Link href="/shop">See everything <ArrowUpRight size={16}/></Link></div><div className="category-grid">{[['Art Prints','Quiet pieces for your walls'],['Handmade','One-of-a-kind studio finds'],['Accessories','Small details to carry'],['Commissions','Bring an idea to life']].map(([x,y],i)=><Link className={'category c'+i} href={x==='Commissions'?'/commissions':'/shop'} key={x}><b>{x}</b><span>{y}</span><ArrowUpRight/></Link>)}</div></section><section className="wrap section featured"><div className="section-heading"><div><p className="eyebrow">FROM THE STUDIO</p><h2>Featured pieces</h2></div><Link href="/shop">Browse shop <ArrowUpRight size={16}/></Link></div>{featured.length?<div className="product-grid">{featured.map(p=><CatalogCard product={p} key={p.id}/>)}</div>:<div className="empty">Featured studio pieces will appear here soon.</div>}</section><section className="commission-band"><div className="wrap"><p className="eyebrow">WORK TOGETHER</p><h2>Have an idea in mind?</h2><p>Tell me about it, and we’ll find the right way to make it real.</p><Link className="button light" href="/commissions">Request a commission <ArrowUpRight size={17}/></Link></div></section></>;
}
