-- Run in the Supabase SQL editor. Replace/add admins by managing public.admin_users.
create table if not exists public.admin_users (user_id uuid primary key references auth.users(id) on delete cascade, email text unique not null, created_at timestamptz default now());
create table if not exists public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, sort_order integer default 0, created_at timestamptz default now());
create table if not exists public.products (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text, price_cents integer not null check(price_cents>=0), category_id uuid references public.categories(id) on delete set null, stock_quantity integer default 0 check(stock_quantity>=0), status text not null default 'draft' check(status in ('draft','published','hidden','sold_out')), featured boolean default false, sort_order integer default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.product_images (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, storage_path text not null, alt_text text, sort_order integer default 0);
create table if not exists public.commissions (id uuid primary key default gen_random_uuid(), name text not null, description text, starting_price_cents integer not null, example_image_path text, available boolean default true, turnaround text, sort_order integer default 0);
create table if not exists public.commission_requests (id uuid primary key default gen_random_uuid(), customer_name text not null, email text not null, commission_id uuid references public.commissions(id) on delete set null, description text not null, preferred_style text, budget_cents integer, notes text, reference_paths text[] default '{}', status text default 'new', created_at timestamptz default now());
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), order_number text unique not null, email text not null, customer_name text, status text not null default 'pending' check(status in ('pending','paid','processing','shipped','completed','cancelled')), total_cents integer not null default 0, payment_reference text, created_at timestamptz default now());
create table if not exists public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id) on delete set null, product_name text not null, unit_price_cents integer not null, quantity integer not null check(quantity>0));
alter table public.admin_users enable row level security; alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.product_images enable row level security; alter table public.commissions enable row level security; alter table public.commission_requests enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.admin_users where user_id=auth.uid())$$;
create policy "public catalogue" on public.products for select using(status='published'); create policy "admin products" on public.products for all using(public.is_admin()) with check(public.is_admin());
create policy "public categories" on public.categories for select using(true); create policy "admin categories" on public.categories for all using(public.is_admin()) with check(public.is_admin());
create policy "public images" on public.product_images for select using(exists(select 1 from public.products p where p.id=product_id and p.status='published')); create policy "admin images" on public.product_images for all using(public.is_admin()) with check(public.is_admin());
create policy "public commissions" on public.commissions for select using(available); create policy "admin commissions" on public.commissions for all using(public.is_admin()) with check(public.is_admin());
create policy "request create" on public.commission_requests for insert with check(true); create policy "admin requests" on public.commission_requests for select using(public.is_admin());
create policy "admin orders" on public.orders for all using(public.is_admin()) with check(public.is_admin()); create policy "admin order items" on public.order_items for all using(public.is_admin()) with check(public.is_admin());
